name: 'Download various files from TAC / TAC-Vérif'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  tests:
    env:
      API_VERSION: 35
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Download 2DDoc blacklist
        run: "curl https://app-static.tousanticovid.gouv.fr/json/version-${API_VERSION}/CertList/2ddoc_list.json | jq '.' &> blacklits_2ddoc.json"
      - name: Download QRCode blacklist
        run: "curl https://app-static.tousanticovid.gouv.fr/json/version-${API_VERSION}/CertList/certlist.json | jq '.' &> blacklist_qrcode.json"
      - name: Download various files
        env:
          FILES:  Calibration/calibrationBle.json Config/config.json Certs/dcc-certs.json Risks/risks.json
        run: "for url in $FILES; do curl https://app-static.tousanticovid.gouv.fr/json/version-${API_VERSION}/${url} | jq --sort-keys '.' &> ${url##*/}; done"
      - name: Download the conf from the TAC-V server
        env:
          token: ${{ secrets.TOKEN }}
        run: "curl -s https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/tacv -H \"Authorization: Bearer ${token}\" | jq --sort-keys '. | del(.currentDate)' &> TAC-V_conf.json"
      - name: Download the countries from the TAC-V server
        env:
          token: ${{ secrets.TOKEN }}
        run: "curl -s https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/countries/tacv -H \"Authorization: Bearer ${token}\" | jq --sort-keys '. | del(.currentDate)' &> TAC-V_countries.json"
      - name: Download the valuesets from the TAC-V server
        env:
          token: ${{ secrets.TOKEN }}
        run: "curl -s https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/valuesets/tacv -H \"Authorization: Bearer ${token}\" | jq --sort-keys '. | del(.currentDate)' &> TAC-V_valuesets.json"
      - name: Download the rules from the TAC-V server
        env:
          token: ${{ secrets.TOKEN }}
        run: "curl -s https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/rules/tacv -H \"Authorization: Bearer ${token}\" | jq --sort-keys '. | del(.currentDate)' &> TAC-V_rules.json"
      - name: Pretty print TAC-V blacklist (qrcodes)
        run: "cat TAC-V_conf.json | jq '. | .specificValues.blacklist.blacklistDCC' |  jq '.' &> blacklist_qrcode_tacv.json"
      - name: Pretty print TAC-V blacklist (2d-doc)
        run: "cat TAC-V_conf.json | jq '. | .specificValues.blacklist.blacklist2DDOC' | jq '.' &> blacklist_2ddoc_tacv.json"
      - name: Pretty print the DCC certificates
        run: "./decode_x509.py TAC-V_conf.json &> certificates.txt"
      - name: Download SNCF blacklist
        run: "curl https://pretavoyager.sncf.com/api/getcertificates | jq '.' &> blacklist_sncf.json"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Update
