name: 'Download various files from TAC / TAC-Vérif'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Download various files
        env:
          FILES: CertList/certlist.json CertList/2ddoc_list.json Calibration/calibrationBle.json Config/config.json Certs/dcc-certs.json Risks/risks.json
        run: "for url in $FILES; do wget -O ${url##*/} https://app-static.tousanticovid.gouv.fr/json/version-35/${url}; done"          
      - name: Download the certificates
        env:
          token: ${{ secrets.TOKEN }}
        run: "curl -s https://portail.tacv.myservices-ingroupe.com/api/client/configuration/synchronisation/tacv -H \"Authorization: Bearer ${token}\" | jq --sort-keys '. | del(.currentDate)' &> certificates.json"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Update
