name: 'Download various files from TAC / TAC-Vérif'
on:
  push:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-21.11
      - name: Download blacklists and various files for the TAC application
        run: "./download_tac.py"
      - name: Download blacklists and various files for the TAC-V application
        run: "./download_tacv.py"
        env:
          token: ${{ secrets.TOKEN }}
      - name: Pretty print the DCC certificates
        run: "./decode_x509.py TAC-V_conf.json &> certificates.txt"
      - name: Pretty print rules
        env:
          token: ${{ secrets.TOKEN }}
        run: "./get_rules.py &> TAC-V_rules-pretty.json"
      - name: Pretty print valuesets
        env:
          token: ${{ secrets.TOKEN }}
        run: "./get_valuesets.py &> TAC-V_valuesets-pretty.json"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic Update
